name: Build React App

on:
  push:
    branches:
      - master
      - dev
      - release

jobs:
  build-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          echo "DevOps dev Engineer"
          echo ${{ github.workspace }}
          cd ${{ github.workspace }} ; npm install

      - name: Build
        run: |
          cd ${{ github.workspace }}
          npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/

  deploy-dev:
    runs-on: deploy-server
    if: github.ref == 'refs/heads/develop'
    needs: build-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/
      - name: Copying the nginx folder
        run: | 
         sudo mv ${{ github.workspace }}/build/* /var/www/html
  build-prod:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/develop'
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          echo "DevOps prod Engineer"
          echo ${{ github.workspace }}
          cd ${{ github.workspace }} ; npm install

      - name: Build
        run: |
          cd ${{ github.workspace }}
          npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/

  prod-dev:
    runs-on: deploy-prod-server
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/
      - name: Copying the nginx folder
        run: | 
         sudo mv ${{ github.workspace }}/build/* /var/www/html         


